[package]
name = "slang-rs"
version = "0.1.0"
edition = "2024"
description = "Rust bindings for the Slang shader language compiler"
license = "MIT OR Apache-2.0"
categories = ["compilers", "api-bindings"]

[dependencies]
slang-rs-sys = { path = "slang-rs-sys", version = "0.1.0" }

[features]
serde = ["slang-rs-sys/serde"]
source-build = ["slang-rs-sys/source-build"]

[workspace]
members = ["slang-rs-sys"]
